// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTd1KdrIb4nIvmEHy0O5MCbK4Cwk21Z7U',
    appId: '1:795065301225:web:87462cf240952b1949d878',
    messagingSenderId: '795065301225',
    projectId: 'dream-sanctuary-42daf',
    authDomain: 'dream-sanctuary-42daf.firebaseapp.com',
    databaseURL: 'https://dream-sanctuary-42daf-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dream-sanctuary-42daf.appspot.com',
    measurementId: 'G-LD53DWNM9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8NgbVaEJDxve_yXxF10lx_RQtHakuC9U',
    appId: '1:795065301225:android:6e78004b06a7c3bf49d878',
    messagingSenderId: '795065301225',
    projectId: 'dream-sanctuary-42daf',
    databaseURL: 'https://dream-sanctuary-42daf-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dream-sanctuary-42daf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBPqAGMgmtS-misionwQ0p8LOdjOoxxXo',
    appId: '1:795065301225:ios:2b6caf0cdcaedca349d878',
    messagingSenderId: '795065301225',
    projectId: 'dream-sanctuary-42daf',
    databaseURL: 'https://dream-sanctuary-42daf-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dream-sanctuary-42daf.appspot.com',
    iosClientId: '795065301225-4q92paqfbrig7ehqrd1smh19ikqss9fg.apps.googleusercontent.com',
    iosBundleId: 'com.example.dreamsanctuary',
  );
}
